# -*- coding: utf-8 -*-
"""Stock predict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xRGKbIXlpW9H845BodNYL7iPtacztn9R
"""

!pip install -q yfinance pandas numpy scikit-learn plotly matplotlib \
             finnhub-python newsapi-python \
             transformers torch sentencepiece

!pip install -q xgboost
from xgboost import XGBClassifier

def train_xgboost(X_train, y_train):
    model = XGBClassifier(
        n_estimators    = 300,
        max_depth       = 6,
        learning_rate   = 0.05,
        subsample       = 0.8,
        colsample_bytree= 0.8,
        use_label_encoder=False,
        eval_metric     = 'logloss',
        random_state    = 42
    )
    model.fit(X_train, y_train)
    print("✅ XGBoost trained!")
    return model

# Re-prepare features with new columns
X, y, scaler                     = prepare_features(df)
X_train, X_test, y_train, y_test = time_split(X, y)

# Train both models
rf_model  = train_model(X_train, y_train)       # Random Forest
xgb_model = train_xgboost(X_train, y_train)     # XGBoost

# Compare
rf_acc  = accuracy_score(y_test, rf_model.predict(X_test))
xgb_acc = accuracy_score(y_test, xgb_model.predict(X_test))

print(f"\n📊 Model Comparison:")
print(f"   Random Forest : {rf_acc*100:.2f}%")
print(f"   XGBoost       : {xgb_acc*100:.2f}%")

from sklearn.ensemble import VotingClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

def train_ensemble(X_train, y_train, X_test, y_test):
    """Combine multiple models — majority vote wins"""

    rf  = RandomForestClassifier(n_estimators=200, max_depth=10,
                                  random_state=42, class_weight='balanced')
    xgb = XGBClassifier(n_estimators=300, max_depth=6, learning_rate=0.05,
                         use_label_encoder=False, eval_metric='logloss',
                         random_state=42)
    gb  = GradientBoostingClassifier(n_estimators=200, max_depth=5,
                                      learning_rate=0.05, random_state=42)
    lr  = LogisticRegression(max_iter=1000, class_weight='balanced')

    ensemble = VotingClassifier(
        estimators=[('rf', rf), ('xgb', xgb), ('gb', gb), ('lr', lr)],
        voting='soft'   # use probabilities for smarter voting
    )
    ensemble.fit(X_train, y_train)

    y_pred   = ensemble.predict(X_test)
    acc      = accuracy_score(y_test, y_pred)

    print(f"✅ Ensemble model trained!")
    print(f"   Accuracy: {acc*100:.2f}%")
    print(f"\n{classification_report(y_test, y_pred, target_names=['DOWN','UP'])}")
    return ensemble, y_pred, acc

ensemble_model, y_pred, acc = train_ensemble(X_train, y_train, X_test, y_test)

from sklearn.ensemble import RandomForestClassifier, VotingClassifier, GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
import numpy as np

# ── FEATURES LIST ─────────────────────────────────────────────────────
FEATURES = [
    'SMA_20', 'SMA_50', 'EMA_20',
    'RSI', 'RSI_Change', 'RSI_Overbought', 'RSI_Oversold',
    'MACD', 'MACD_Signal', 'MACD_Hist', 'MACD_Cross', 'MACD_Change',
    'BB_Upper', 'BB_Lower', 'BB_Width',
    'Mom_5', 'Mom_10', 'Mom_30',
    'Vol_Ratio', 'Vol_Spike', 'Vol_Change',
    'sentiment_score',
    'Price_Range', 'Gap', 'Body',
    'Volatility_10', 'Volatility_20',
    'SMA_Cross', 'Price_vs_SMA20', 'Price_vs_SMA50',
    'Close_Lag_1', 'Close_Lag_2', 'Close_Lag_3', 'Close_Lag_5',
    'Return_Lag_1', 'Return_Lag_2', 'Return_Lag_3', 'Return_Lag_5',
    'DayOfWeek'
]

# ── Verify all features exist ─────────────────────────────────────────
missing = [f for f in FEATURES if f not in df.columns]
if missing:
    print(f"❌ Missing columns: {missing}")
    print("   Re-run add_indicators() and add_advanced_indicators() first!")
else:
    print(f"✅ All {len(FEATURES)} features present in df!")

# ── prepare_features ─────────────────────────────────────────────────
def prepare_features(df):
    X        = df[FEATURES].copy()
    y        = df['Target'].copy()
    scaler   = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    X_scaled = pd.DataFrame(X_scaled, columns=FEATURES, index=X.index)
    print(f"✅ Features prepared! X: {X_scaled.shape}, y: {y.shape}")
    return X_scaled, y, scaler

# ── time_split ────────────────────────────────────────────────────────
def time_split(X, y, test_ratio=0.2):
    split   = int(len(X) * (1 - test_ratio))
    X_train = X.iloc[:split];  X_test  = X.iloc[split:]
    y_train = y.iloc[:split];  y_test  = y.iloc[split:]
    print(f"✅ Train: {len(X_train)} rows | Test: {len(X_test)} rows")
    return X_train, X_test, y_train, y_test

# ── train_model (Random Forest) ───────────────────────────────────────
def train_model(X_train, y_train):
    model = RandomForestClassifier(
        n_estimators=200, max_depth=10,
        min_samples_split=10, random_state=42,
        class_weight='balanced'
    )
    model.fit(X_train, y_train)
    print("✅ Random Forest trained!")
    return model

# ── train_xgboost ─────────────────────────────────────────────────────
def train_xgboost(X_train, y_train):
    model = XGBClassifier(
        n_estimators=300, max_depth=6,
        learning_rate=0.05, subsample=0.8,
        colsample_bytree=0.8,
        eval_metric='logloss', random_state=42
    )
    model.fit(X_train, y_train)
    print("✅ XGBoost trained!")
    return model

# ── train_ensemble ────────────────────────────────────────────────────
def train_ensemble(X_train, y_train, X_test, y_test):
    rf  = RandomForestClassifier(n_estimators=200, max_depth=10,
                                  random_state=42, class_weight='balanced')
    xgb = XGBClassifier(n_estimators=300, max_depth=6, learning_rate=0.05,
                         eval_metric='logloss', random_state=42)
    gb  = GradientBoostingClassifier(n_estimators=200, max_depth=5,
                                      learning_rate=0.05, random_state=42)
    lr  = LogisticRegression(max_iter=1000, class_weight='balanced')

    ensemble = VotingClassifier(
        estimators=[('rf', rf), ('xgb', xgb), ('gb', gb), ('lr', lr)],
        voting='soft'
    )
    ensemble.fit(X_train, y_train)
    y_pred = ensemble.predict(X_test)
    acc    = accuracy_score(y_test, y_pred)
    print(f"✅ Ensemble trained! Accuracy: {acc*100:.2f}%")
    print(classification_report(y_test, y_pred, target_names=['DOWN','UP']))
    return ensemble, y_pred, acc

# ── create_target ─────────────────────────────────────────────────────
def create_target(df, days_ahead=1):
    df           = df.copy()
    df['Target'] = (df['Close'].shift(-days_ahead) > df['Close']).astype(int)
    df.dropna(inplace=True)
    print(f"✅ Target created! UP: {df['Target'].sum()} | DOWN: {(df['Target']==0).sum()}")
    return df

print("✅ All functions defined!")

# ── Run everything ────────────────────────────────────────────────────
df                               = create_target(df)
X, y, scaler                     = prepare_features(df)
X_train, X_test, y_train, y_test = time_split(X, y)

rf_model                         = train_model(X_train, y_train)
xgb_model                        = train_xgboost(X_train, y_train)
ensemble_model, y_pred, acc      = train_ensemble(X_train, y_train, X_test, y_test)

rf_acc  = accuracy_score(y_test, rf_model.predict(X_test))
xgb_acc = accuracy_score(y_test, xgb_model.predict(X_test))

print(f"\n📊 Model Comparison:")
print(f"   Random Forest : {rf_acc*100:.2f}%")
print(f"   XGBoost       : {xgb_acc*100:.2f}%")
print(f"   Ensemble      : {acc*100:.2f}%")

# ═══════════════════════════════════════════════════════════════════
#  MASTER CELL — Run this once to rebuild everything from scratch
# ═══════════════════════════════════════════════════════════════════

import yfinance as yf
import pandas as pd
import numpy as np
import finnhub
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
from transformers import pipeline
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
import warnings
warnings.filterwarnings('ignore')

TICKER      = "AAPL"          # 🔁 change ticker here
FINNHUB_KEY = "d6qql8pr01qgdhqc0qigd6qql8pr01qgdhqc0qj0" # 🔑 your Finnhub key

# ── FEATURES ──────────────────────────────────────────────────────
FEATURES = [
    'SMA_20', 'SMA_50', 'EMA_20',
    'RSI', 'RSI_Change', 'RSI_Overbought', 'RSI_Oversold',
    'MACD', 'MACD_Signal', 'MACD_Hist', 'MACD_Cross', 'MACD_Change',
    'BB_Upper', 'BB_Lower', 'BB_Width',
    'Mom_5', 'Mom_10', 'Mom_30',
    'Vol_Ratio', 'Vol_Spike', 'Vol_Change',
    'sentiment_score',
    'Price_Range', 'Gap', 'Body',
    'Volatility_10', 'Volatility_20',
    'SMA_Cross', 'Price_vs_SMA20', 'Price_vs_SMA50',
    'Close_Lag_1', 'Close_Lag_2', 'Close_Lag_3', 'Close_Lag_5',
    'Return_Lag_1', 'Return_Lag_2', 'Return_Lag_3', 'Return_Lag_5',
    'DayOfWeek'
]

INDIAN_COMPANIES = {
    "RELIANCE.NS": "Reliance Industries",
    "TCS.NS": "Tata Consultancy Services",
    "INFY.NS": "Infosys", "HDFCBANK.NS": "HDFC Bank",
    "WIPRO.NS": "Wipro", "ICICIBANK.NS": "ICICI Bank",
    "TATAMOTORS.NS": "Tata Motors", "ADANIENT.NS": "Adani Enterprises",
    "SBIN.NS": "State Bank of India", "BAJFINANCE.NS": "Bajaj Finance",
    "ASIANPAINT.NS": "Asian Paints"
}

# ── STEP 1: Fetch Stock Data ───────────────────────────────────────
def fetch_stock_data(ticker_symbol, period="1y"):
    ticker = yf.Ticker(ticker_symbol)
    df     = ticker.history(period=period)
    df.dropna(inplace=True)
    df.index = pd.to_datetime(df.index)
    print(f"✅ Stock data fetched: {len(df)} rows")
    return df

# ── STEP 2: Base Indicators ────────────────────────────────────────
def add_indicators(df):
    df['SMA_20']      = df['Close'].rolling(20).mean()
    df['SMA_50']      = df['Close'].rolling(50).mean()
    df['EMA_20']      = df['Close'].ewm(span=20, adjust=False).mean()
    delta             = df['Close'].diff()
    gain              = delta.clip(lower=0)
    loss              = -delta.clip(upper=0)
    df['RSI']         = 100 - (100 / (1 + gain.rolling(14).mean() / loss.rolling(14).mean()))
    ema12             = df['Close'].ewm(span=12, adjust=False).mean()
    ema26             = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD']        = ema12 - ema26
    df['MACD_Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
    df['MACD_Hist']   = df['MACD'] - df['MACD_Signal']
    rm                = df['Close'].rolling(20).mean()
    rs                = df['Close'].rolling(20).std()
    df['BB_Upper']    = rm + 2 * rs
    df['BB_Lower']    = rm - 2 * rs
    df['BB_Width']    = df['BB_Upper'] - df['BB_Lower']
    df['Mom_5']       = df['Close'].pct_change(5)
    df['Mom_10']      = df['Close'].pct_change(10)
    df['Mom_30']      = df['Close'].pct_change(30)
    df['Vol_MA_10']   = df['Volume'].rolling(10).mean()
    df['Vol_Ratio']   = df['Volume'] / df['Vol_MA_10']
    df.dropna(inplace=True)
    print(f"✅ Base indicators added")
    return df

# ── STEP 3: Advanced Indicators ────────────────────────────────────
def add_advanced_indicators(df):
    df['Price_Range']    = df['High'] - df['Low']
    df['Gap']            = df['Open'] - df['Close'].shift(1)
    df['Body']           = abs(df['Close'] - df['Open'])
    df['Volatility_10']  = df['Close'].pct_change().rolling(10).std() * 100
    df['Volatility_20']  = df['Close'].pct_change().rolling(20).std() * 100
    df['SMA_Cross']      = (df['SMA_20'] - df['SMA_50']) / df['SMA_50'] * 100
    df['Price_vs_SMA20'] = (df['Close']  - df['SMA_20']) / df['SMA_20'] * 100
    df['Price_vs_SMA50'] = (df['Close']  - df['SMA_50']) / df['SMA_50'] * 100
    df['RSI_Overbought'] = (df['RSI'] > 70).astype(int)
    df['RSI_Oversold']   = (df['RSI'] < 30).astype(int)
    df['RSI_Change']     = df['RSI'].diff()
    df['MACD_Cross']     = (df['MACD'] > df['MACD_Signal']).astype(int)
    df['MACD_Change']    = df['MACD_Hist'].diff()
    df['Vol_Spike']      = (df['Vol_Ratio'] > 2).astype(int)
    df['Vol_Change']     = df['Volume'].pct_change()
    for lag in [1, 2, 3, 5]:
        df[f'Close_Lag_{lag}']  = df['Close'].shift(lag)
        df[f'Return_Lag_{lag}'] = df['Close'].pct_change(lag)
    df['DayOfWeek']      = df.index.dayofweek
    df.dropna(inplace=True)
    print(f"✅ Advanced indicators added")
    return df

# ── STEP 4: News & Sentiment ───────────────────────────────────────
def fetch_news_finnhub(ticker_symbol, days_back=30):
    client     = finnhub.Client(api_key=FINNHUB_KEY)
    end_date   = datetime.today().strftime('%Y-%m-%d')
    start_date = (datetime.today() - timedelta(days=days_back)).strftime('%Y-%m-%d')
    news       = client.company_news(ticker_symbol, _from=start_date, to=end_date)

    if len(news) == 0:
        if ticker_symbol in INDIAN_COMPANIES:
            company_name = INDIAN_COMPANIES[ticker_symbol]
        else:
            try:
                info         = yf.Ticker(ticker_symbol).info
                company_name = info.get('longName', ticker_symbol.replace('.NS',''))
            except:
                company_name = ticker_symbol.replace('.NS','').replace('.BO','')
        news = client.general_news('general', min_id=0)
        news = [n for n in news if company_name.lower().split()[0]
                in n.get('headline','').lower()]

    headlines = []
    for article in news:
        try:
            headlines.append({
                'date'    : datetime.fromtimestamp(article['datetime']).strftime('%Y-%m-%d'),
                'headline': article['headline'],
                'source'  : article['source'],
                'summary' : article.get('summary', '')
            })
        except:
            continue

    if not headlines:
        headlines = [{'date': datetime.today().strftime('%Y-%m-%d'),
                      'headline': f'{ticker_symbol} stock', 'source': 'fallback', 'summary': ''}]

    news_df = pd.DataFrame(headlines).drop_duplicates(subset='headline')
    print(f"✅ Fetched {len(news_df)} news articles")
    return news_df

def analyze_sentiment(news_df):
    news_df = news_df[['date','headline','source','summary']].copy()
    labels, confidences = [], []
    for _, row in news_df.iterrows():
        try:
            result = finbert(str(row['headline'])[:512])[0]
            labels.append(result['label'].lower().strip())
            confidences.append(round(result['score'], 4))
        except:
            labels.append('neutral')
            confidences.append(0.5)
    news_df['label']      = labels
    news_df['confidence'] = confidences
    print("✅ Sentiment done:", news_df['label'].value_counts().to_dict())
    return news_df

def get_daily_sentiment(news_df):
    label_map        = {'positive': 1, 'neutral': 0, 'negative': -1}
    news_df['score'] = news_df['label'].map(label_map) * news_df['confidence']
    daily            = (news_df.groupby('date')['score'].mean()
                        .reset_index().rename(columns={'score':'sentiment_score'}))
    daily['date']    = pd.to_datetime(daily['date'])
    print(f"✅ Daily sentiment: {len(daily)} days")
    return daily

def merge_sentiment_with_stock(df, daily_sentiment):
    df            = df.copy()
    df['date_dt'] = pd.to_datetime(df.index.strftime('%Y-%m-%d'))
    merged        = pd.merge_asof(
        df.sort_values('date_dt'),
        daily_sentiment.rename(columns={'date':'date_dt'}),
        on='date_dt', direction='backward'
    )
    merged['sentiment_score'] = merged['sentiment_score'].fillna(0)
    merged.index              = df.index
    merged.drop(columns=['date_dt'], inplace=True)
    print(f"✅ Sentiment merged! Shape: {merged.shape}")
    return merged

# ── STEP 5: ML Functions ───────────────────────────────────────────
def create_target(df, days_ahead=1):
    df           = df.copy()
    df['Target'] = (df['Close'].shift(-days_ahead) > df['Close']).astype(int)
    df.dropna(inplace=True)
    print(f"✅ Target: UP={df['Target'].sum()} DOWN={(df['Target']==0).sum()}")
    return df

def prepare_features(df):
    X        = df[FEATURES].copy()
    y        = df['Target'].copy()
    scaler   = StandardScaler()
    X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=FEATURES, index=X.index)
    print(f"✅ Features ready: {X_scaled.shape}")
    return X_scaled, y, scaler

def time_split(X, y, test_ratio=0.2):
    split   = int(len(X) * (1 - test_ratio))
    print(f"✅ Train: {split} | Test: {len(X)-split}")
    return X.iloc[:split], X.iloc[split:], y.iloc[:split], y.iloc[split:]

def train_model(X_train, y_train):
    m = RandomForestClassifier(n_estimators=200, max_depth=10,
                                random_state=42, class_weight='balanced')
    m.fit(X_train, y_train)
    print("✅ Random Forest trained!")
    return m

def train_xgboost(X_train, y_train):
    m = XGBClassifier(n_estimators=300, max_depth=6, learning_rate=0.05,
                       subsample=0.8, colsample_bytree=0.8,
                       eval_metric='logloss', random_state=42)
    m.fit(X_train, y_train)
    print("✅ XGBoost trained!")
    return m

def train_ensemble(X_train, y_train, X_test, y_test):
    ensemble = VotingClassifier(estimators=[
        ('rf',  RandomForestClassifier(n_estimators=200, max_depth=10,
                                        random_state=42, class_weight='balanced')),
        ('xgb', XGBClassifier(n_estimators=300, max_depth=6, learning_rate=0.05,
                               eval_metric='logloss', random_state=42)),
        ('gb',  GradientBoostingClassifier(n_estimators=200, max_depth=5,
                                            learning_rate=0.05, random_state=42)),
        ('lr',  LogisticRegression(max_iter=1000, class_weight='balanced'))
    ], voting='soft')
    ensemble.fit(X_train, y_train)
    y_pred = ensemble.predict(X_test)
    acc    = accuracy_score(y_test, y_pred)
    print(f"✅ Ensemble trained! Accuracy: {acc*100:.2f}%")
    print(classification_report(y_test, y_pred, target_names=['DOWN','UP']))
    return ensemble, y_pred, acc

print("✅ All functions defined! Starting full pipeline...\n")

# ═══════════════════════════════════════════════════════════════════
#  RUN FULL PIPELINE
# ═══════════════════════════════════════════════════════════════════

# 1. Stock data + indicators
df = fetch_stock_data(TICKER)
df = add_indicators(df)
df = add_advanced_indicators(df)

# 2. News + sentiment (finbert must already be loaded)
news_df        = fetch_news_finnhub(TICKER, days_back=30)
news_df        = analyze_sentiment(news_df)
daily_sent     = get_daily_sentiment(news_df)
df             = merge_sentiment_with_stock(df, daily_sent)

# 3. Train models
df                               = create_target(df)
X, y, scaler                     = prepare_features(df)
X_train, X_test, y_train, y_test = time_split(X, y)
rf_model                         = train_model(X_train, y_train)
xgb_model                        = train_xgboost(X_train, y_train)
ensemble_model, y_pred, acc      = train_ensemble(X_train, y_train, X_test, y_test)

print(f"\n📊 Final Model Comparison:")
print(f"   Random Forest : {accuracy_score(y_test, rf_model.predict(X_test))*100:.2f}%")
print(f"   XGBoost       : {accuracy_score(y_test, xgb_model.predict(X_test))*100:.2f}%")
print(f"   Ensemble      : {acc*100:.2f}%")



import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from transformers import pipeline
import finnhub
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

print("✅ All imports successful!")
print(f"   NumPy  : {np.__version__}")
print(f"   Pandas : {pd.__version__}")



FINNHUB_KEY = "d6qql8pr01qgdhqc0qigd6qql8pr01qgdhqc0qj0"

# Test Finnhub with a US stock (free tier only supports US quotes)
client = finnhub.Client(api_key=FINNHUB_KEY)
quote  = client.quote("AAPL")
print(f"✅ Finnhub connected! Test: AAPL = ${quote['c']}")

# Test yfinance with Indian stock
test_indian = yf.Ticker("ASIANPAINT.NS")
price       = test_indian.history(period="1d")['Close'].iloc[-1]
print(f"✅ yfinance connected! Asian paint = ₹{price:.2f}")

INDIAN_COMPANIES = {
    "RELIANCE.NS"  : "Reliance Industries",
    "TCS.NS"       : "Tata Consultancy Services",
    "INFY.NS"      : "Infosys",
    "HDFCBANK.NS"  : "HDFC Bank",
    "WIPRO.NS"     : "Wipro",
    "ICICIBANK.NS" : "ICICI Bank",
    "TATAMOTORS.NS": "Tata Motors",
    "ADANIENT.NS"  : "Adani Enterprises",
    "SBIN.NS"      : "State Bank of India",
    "BAJFINANCE.NS": "Bajaj Finance",
    "ASIANPAINT.NS": "Asian Paints"
}
print("✅ Indian companies map loaded!")

INDIAN_COMPANIES = {
    "RELIANCE.NS"  : "Reliance Industries",
    "TCS.NS"       : "Tata Consultancy Services",
    "INFY.NS"      : "Infosys",
    "HDFCBANK.NS"  : "HDFC Bank",
    "WIPRO.NS"     : "Wipro",
    "ICICIBANK.NS" : "ICICI Bank",
    "TATAMOTORS.NS": "Tata Motors",
    "ADANIENT.NS"  : "Adani Enterprises",
    "SBIN.NS"      : "State Bank of India",
    "BAJFINANCE.NS": "Bajaj Finance"
}

def fetch_stock_data(ticker_symbol, period="1y"):
    ticker = yf.Ticker(ticker_symbol)
    df     = ticker.history(period=period)
    df.dropna(inplace=True)
    df.index = pd.to_datetime(df.index)
    print(f"✅ Fetched {len(df)} rows for {ticker_symbol}")
    return df

TICKER = "AAPL"   # 🔁 change to any ticker e.g. TSLA, RELIANCE.NS
df     = fetch_stock_data(TICKER)
df[['Open', 'High', 'Low', 'Close', 'Volume']].tail(5)

def add_indicators(df):
    # Moving Averages
    df['SMA_20']      = df['Close'].rolling(20).mean()
    df['SMA_50']      = df['Close'].rolling(50).mean()
    df['EMA_20']      = df['Close'].ewm(span=20, adjust=False).mean()

    # RSI
    delta             = df['Close'].diff()
    gain              = delta.clip(lower=0)
    loss              = -delta.clip(upper=0)
    avg_gain          = gain.rolling(14).mean()
    avg_loss          = loss.rolling(14).mean()
    rs                = avg_gain / avg_loss
    df['RSI']         = 100 - (100 / (1 + rs))

    # MACD
    ema12             = df['Close'].ewm(span=12, adjust=False).mean()
    ema26             = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD']        = ema12 - ema26
    df['MACD_Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
    df['MACD_Hist']   = df['MACD'] - df['MACD_Signal']

    # Bollinger Bands
    rm                = df['Close'].rolling(20).mean()
    rs                = df['Close'].rolling(20).std()
    df['BB_Upper']    = rm + 2 * rs
    df['BB_Lower']    = rm - 2 * rs
    df['BB_Width']    = df['BB_Upper'] - df['BB_Lower']

    # Momentum
    df['Mom_5']       = df['Close'].pct_change(5)
    df['Mom_10']      = df['Close'].pct_change(10)
    df['Mom_30']      = df['Close'].pct_change(30)

    # Volume
    df['Vol_MA_10']   = df['Volume'].rolling(10).mean()
    df['Vol_Ratio']   = df['Volume'] / df['Vol_MA_10']

    df.dropna(inplace=True)
    print(f"✅ Indicators added! Shape: {df.shape}")
    return df

df = add_indicators(df)
df[['Close', 'SMA_20', 'SMA_50', 'RSI', 'MACD']].tail(5)

def plot_indicators(df, ticker_symbol):
    fig = make_subplots(
        rows=3, cols=1,
        shared_xaxes=True,
        row_heights=[0.5, 0.25, 0.25],
        subplot_titles=(f"{ticker_symbol} Price + Bollinger Bands", "RSI", "MACD")
    )

    # Price + Bands
    fig.add_trace(go.Candlestick(x=df.index, open=df['Open'], high=df['High'],
                                  low=df['Low'], close=df['Close'], name='Price'), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df['SMA_20'], name='SMA 20',
                              line=dict(color='orange')), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df['SMA_50'], name='SMA 50',
                              line=dict(color='blue')), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df['BB_Upper'], name='BB Upper',
                              line=dict(color='grey', dash='dash')), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df['BB_Lower'], name='BB Lower',
                              line=dict(color='grey', dash='dash'),
                              fill='tonexty', fillcolor='rgba(128,128,128,0.1)'), row=1, col=1)

    # RSI
    fig.add_trace(go.Scatter(x=df.index, y=df['RSI'], name='RSI',
                              line=dict(color='purple')), row=2, col=1)
    fig.add_hline(y=70, line_dash="dash", line_color="red",   row=2, col=1)
    fig.add_hline(y=30, line_dash="dash", line_color="green", row=2, col=1)

    # MACD
    fig.add_trace(go.Scatter(x=df.index, y=df['MACD'],        name='MACD',
                              line=dict(color='blue')),   row=3, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df['MACD_Signal'], name='Signal',
                              line=dict(color='orange')), row=3, col=1)
    fig.add_trace(go.Bar(x=df.index, y=df['MACD_Hist'],       name='Histogram',
                          marker_color='grey'),           row=3, col=1)

    fig.update_layout(height=800, template='plotly_dark',
                      xaxis_rangeslider_visible=False)
    fig.show()

plot_indicators(df, TICKER)

print("⏳ Loading FinBERT model...")
finbert = pipeline(
    "text-classification",
    model="ProsusAI/finbert",
    tokenizer="ProsusAI/finbert",
    device=-1   # CPU — works on all Colab instances
)
print("✅ FinBERT loaded!")

# Sanity test
test = finbert("Apple reports record breaking quarterly earnings")[0]
print(f"   Test → label: {test['label']}, confidence: {test['score']:.4f}")

# Map of Indian tickers to company names for better news search
INDIAN_COMPANIES = {
    "RELIANCE.NS" : "Reliance Industries",
    "TCS.NS"      : "Tata Consultancy Services",
    "INFY.NS"     : "Infosys",
    "HDFCBANK.NS" : "HDFC Bank",
    "WIPRO.NS"    : "Wipro",
    "ICICIBANK.NS": "ICICI Bank",
    "TATAMOTORS.NS": "Tata Motors",
    "ADANIENT.NS" : "Adani Enterprises",
    "SBIN.NS"     : "State Bank of India",
    "BAJFINANCE.NS": "Bajaj Finance"
}

def fetch_news_finnhub(ticker_symbol, days_back=30):
    client     = finnhub.Client(api_key=FINNHUB_KEY)
    end_date   = datetime.today().strftime('%Y-%m-%d')
    start_date = (datetime.today() - timedelta(days=days_back)).strftime('%Y-%m-%d')

    # Try direct ticker first
    news = client.company_news(ticker_symbol, _from=start_date, to=end_date)

    # If no results (common for Indian stocks), search by company name
    if len(news) == 0:
        print(f"⚠️  No Finnhub news for {ticker_symbol}, switching to keyword search...")

        # Get company name — from map or from yfinance
        if ticker_symbol in INDIAN_COMPANIES:
            company_name = INDIAN_COMPANIES[ticker_symbol]
        else:
            try:
                info         = yf.Ticker(ticker_symbol).info
                company_name = info.get('longName', ticker_symbol.replace('.NS','').replace('.BO',''))
            except:
                company_name = ticker_symbol.replace('.NS','').replace('.BO','')

        print(f"   Searching news for: {company_name}")

        # Use Finnhub general news search
        news = client.general_news('general', min_id=0)
        news = [n for n in news if
                company_name.lower().split()[0] in n.get('headline','').lower() or
                company_name.lower().split()[0] in n.get('summary','').lower()]

    headlines = []
    for article in news:
        try:
            headlines.append({
                'date'    : datetime.fromtimestamp(article['datetime']).strftime('%Y-%m-%d'),
                'headline': article['headline'],
                'source'  : article['source'],
                'summary' : article.get('summary', '')
            })
        except:
            continue

    news_df = pd.DataFrame(headlines).drop_duplicates(subset='headline') \
              if headlines else pd.DataFrame(columns=['date','headline','source','summary'])

    if len(news_df) == 0:
        print(f"⚠️  No news found — using neutral sentiment")
        news_df = pd.DataFrame([{
            'date'    : datetime.today().strftime('%Y-%m-%d'),
            'headline': f'{ticker_symbol} stock analysis',
            'source'  : 'fallback',
            'summary' : ''
        }])

    print(f"✅ Fetched {len(news_df)} articles for {ticker_symbol}")
    return news_df

def analyze_sentiment(news_df):
    news_df   = news_df[['date', 'headline', 'source', 'summary']].copy()
    labels, confidences = [], []

    for _, row in news_df.iterrows():
        try:
            text = str(row['headline'])[:512]
            result = finbert(text)[0]
            labels.append(result['label'].lower().strip())
            confidences.append(round(result['score'], 4))
        except Exception as e:
            labels.append('neutral')
            confidences.append(0.5)

    news_df['label']      = labels
    news_df['confidence'] = confidences
    print("✅ Sentiment done!")
    print("Label distribution:", news_df['label'].value_counts().to_dict())
    return news_df

news_df = analyze_sentiment(news_df)
news_df[['date', 'headline', 'label', 'confidence']].head(10)

def add_indicators(df):
    # ... your existing indicators ...

    # ── NEW: Candlestick Patterns ──────────────────
    df['Doji']        = (abs(df['Close'] - df['Open']) / (df['High'] - df['Low'] + 0.001) < 0.1).astype(int)
    df['Hammer']      = ((df['High'] - df['Low']) > 3 * abs(df['Open'] - df['Close'])).astype(int)

    # ── NEW: Price position within day's range ─────
    df['Price_Range'] = (df['Close'] - df['Low']) / (df['High'] - df['Low'] + 0.001)

    # ── NEW: Gap up/down from previous close ───────
    df['Gap']         = (df['Open'] - df['Close'].shift(1)) / df['Close'].shift(1)

    # ── NEW: Volatility ────────────────────────────
    df['Volatility']  = df['Close'].rolling(10).std() / df['Close'].rolling(10).mean()

    # ── NEW: Day of week (Mon=0, Fri=4) ───────────
    df['DayOfWeek']   = df.index.dayofweek

    df.dropna(inplace=True)
    return df

def get_daily_sentiment(news_df):
    label_map        = {'positive': 1, 'neutral': 0, 'negative': -1}
    news_df['score'] = news_df['label'].map(label_map) * news_df['confidence']

    daily = (
        news_df.groupby('date')['score']
        .mean()
        .reset_index()
        .rename(columns={'score': 'sentiment_score'})
    )
    daily['date'] = pd.to_datetime(daily['date'])
    print(f"✅ Daily sentiment for {len(daily)} days:")
    print(daily.tail(10))
    return daily

def merge_sentiment_with_stock(df, daily_sentiment):
    df         = df.copy()
    df['date_dt'] = pd.to_datetime(df.index.strftime('%Y-%m-%d'))

    merged = pd.merge_asof(
        df.sort_values('date_dt'),
        daily_sentiment.rename(columns={'date': 'date_dt'}),
        on='date_dt',
        direction='backward'
    )
    merged['sentiment_score'] = merged['sentiment_score'].fillna(0)
    merged.index = df.index
    merged.drop(columns=['date_dt'], inplace=True)
    print(f"✅ Merged! Shape: {merged.shape}")
    return merged

daily_sentiment = get_daily_sentiment(news_df)
df              = merge_sentiment_with_stock(df, daily_sentiment)
df[['Close', 'RSI', 'MACD', 'sentiment_score']].tail(10)

def plot_sentiment(daily_sentiment):
    colors = ['green' if s > 0 else 'red' if s < 0 else 'grey'
              for s in daily_sentiment['sentiment_score']]
    fig = go.Figure(go.Bar(
        x=daily_sentiment['date'],
        y=daily_sentiment['sentiment_score'],
        marker_color=colors
    ))
    fig.update_layout(
        title=f"📰 Daily News Sentiment — {TICKER}",
        xaxis_title="Date",
        yaxis_title="Sentiment Score (-1 to +1)",
        template="plotly_dark",
        yaxis=dict(range=[-1, 1])
    )
    fig.show()

plot_sentiment(daily_sentiment)

def create_target(df, days_ahead=1):
    """
    Target = 1 if price goes UP tomorrow, 0 if DOWN
    """
    df          = df.copy()
    df['Target'] = (df['Close'].shift(-days_ahead) > df['Close']).astype(int)
    df.dropna(inplace=True)
    print(f"✅ Target created!")
    print(f"   UP   (1): {df['Target'].sum()} days")
    print(f"   DOWN (0): {(df['Target'] == 0).sum()} days")
    return df

df = create_target(df, days_ahead=1)
df[['Close', 'RSI', 'MACD', 'sentiment_score', 'Target']].tail(10)

FEATURES = [
    # Original indicators
    'SMA_20', 'SMA_50', 'EMA_20',
    'RSI', 'RSI_Change', 'RSI_Overbought', 'RSI_Oversold',
    'MACD', 'MACD_Signal', 'MACD_Hist', 'MACD_Cross', 'MACD_Change',
    'BB_Upper', 'BB_Lower', 'BB_Width',
    'Mom_5', 'Mom_10', 'Mom_30',
    'Vol_Ratio', 'Vol_Spike', 'Vol_Change',
    'sentiment_score',

    # New advanced features
    'Price_Range', 'Gap', 'Body',
    'Volatility_10', 'Volatility_20',
    'SMA_Cross', 'Price_vs_SMA20', 'Price_vs_SMA50',
    'Close_Lag_1', 'Close_Lag_2', 'Close_Lag_3', 'Close_Lag_5',
    'Return_Lag_1', 'Return_Lag_2', 'Return_Lag_3', 'Return_Lag_5',
    'DayOfWeek'
]

# Verify
missing = [f for f in FEATURES if f not in df.columns]
if missing:
    print(f"❌ Still missing: {missing}")
else:
    print(f"✅ All {len(FEATURES)} features present!")

def prepare_features(df):
    X = df[FEATURES].copy()
    y = df['Target'].copy()

    # Normalize features to same scale
    from sklearn.preprocessing import StandardScaler
    scaler  = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    X_scaled = pd.DataFrame(X_scaled, columns=FEATURES, index=X.index)

    print(f"✅ Features prepared!")
    print(f"   X shape : {X_scaled.shape}")
    print(f"   y shape : {y.shape}")
    return X_scaled, y, scaler

X, y, scaler = prepare_features(df)

def add_advanced_indicators(df):
    """Add extra features on top of existing ones"""
    df = df.copy()

    # ── Price Action ─────────────────────────────────────────
    df['Price_Range']   = df['High'] - df['Low']           # daily range
    df['Gap']           = df['Open'] - df['Close'].shift(1) # gap up/down
    df['Body']          = abs(df['Close'] - df['Open'])     # candle body size

    # ── Volatility ───────────────────────────────────────────
    df['Volatility_10'] = df['Close'].pct_change().rolling(10).std() * 100
    df['Volatility_20'] = df['Close'].pct_change().rolling(20).std() * 100

    # ── Trend Strength ────────────────────────────────────────
    df['SMA_Cross']     = (df['SMA_20'] - df['SMA_50']) / df['SMA_50'] * 100
    df['Price_vs_SMA20']= (df['Close']  - df['SMA_20']) / df['SMA_20'] * 100
    df['Price_vs_SMA50']= (df['Close']  - df['SMA_50']) / df['SMA_50'] * 100

    # ── RSI Signals ───────────────────────────────────────────
    df['RSI_Overbought']= (df['RSI'] > 70).astype(int)
    df['RSI_Oversold']  = (df['RSI'] < 30).astype(int)
    df['RSI_Change']    = df['RSI'].diff()

    # ── MACD Signal ───────────────────────────────────────────
    df['MACD_Cross']    = (df['MACD'] > df['MACD_Signal']).astype(int)
    df['MACD_Change']   = df['MACD_Hist'].diff()

    # ── Volume Signals ────────────────────────────────────────
    df['Vol_Spike']     = (df['Vol_Ratio'] > 2).astype(int)  # volume surge
    df['Vol_Change']    = df['Volume'].pct_change()

    # ── Lag Features (past prices as features) ────────────────
    for lag in [1, 2, 3, 5]:
        df[f'Close_Lag_{lag}']  = df['Close'].shift(lag)
        df[f'Return_Lag_{lag}'] = df['Close'].pct_change(lag)

    # ── Day of Week (Monday=0, Friday=4) ─────────────────────
    df['DayOfWeek']     = df.index.dayofweek

    df.dropna(inplace=True)
    print(f"✅ Advanced indicators added! Shape: {df.shape}")
    return df


# Run on your existing df
df = add_advanced_indicators(df)
print("New columns added:", df.shape[1])

def time_split(X, y, test_ratio=0.2):
    """
    Split keeping time order — never shuffle stock data!
    Last 20% of data = test set
    """
    split     = int(len(X) * (1 - test_ratio))
    X_train   = X.iloc[:split]
    X_test    = X.iloc[split:]
    y_train   = y.iloc[:split]
    y_test    = y.iloc[split:]

    print(f"✅ Split done!")
    print(f"   Train: {len(X_train)} rows  ({X_train.index[0].date()} → {X_train.index[-1].date()})")
    print(f"   Test : {len(X_test)}  rows  ({X_test.index[0].date()} → {X_test.index[-1].date()})")
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = time_split(X, y)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

def train_model(X_train, y_train):
    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        min_samples_split=10,
        random_state=42,
        class_weight='balanced'   # handles unequal UP/DOWN distribution
    )
    model.fit(X_train, y_train)
    print("✅ Model trained!")
    return model

model = train_model(X_train, y_train)

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    acc    = accuracy_score(y_test, y_pred)

    print(f"✅ Model Evaluation:")
    print(f"   Accuracy : {acc * 100:.2f}%")
    print(f"\n{classification_report(y_test, y_pred, target_names=['DOWN', 'UP'])}")
    return y_pred

y_pred = evaluate_model(model, X_test, y_test)

def plot_feature_importance(model):
    importance = pd.Series(
        model.feature_importances_,
        index=FEATURES
    ).sort_values(ascending=True)

    fig = go.Figure(go.Bar(
        x=importance.values,
        y=importance.index,
        orientation='h',
        marker_color='steelblue'
    ))
    fig.update_layout(
        title="🔍 Feature Importance — What drives predictions?",
        xaxis_title="Importance Score",
        template="plotly_dark",
        height=500
    )
    fig.show()

plot_feature_importance(model)

def predict_tomorrow(model, df, scaler):
    """Use the most recent day's data to predict tomorrow"""
    latest      = df[FEATURES].iloc[-1:]
    latest_scaled = scaler.transform(latest)

    prediction  = model.predict(latest_scaled)[0]
    probability = model.predict_proba(latest_scaled)[0]

    direction   = "📈 UP" if prediction == 1 else "📉 DOWN"
    confidence  = max(probability) * 100

    print(f"\n🔮 Prediction for tomorrow ({TICKER}):")
    print(f"   Direction  : {direction}")
    print(f"   Confidence : {confidence:.1f}%")
    print(f"   UP prob    : {probability[1]*100:.1f}%")
    print(f"   DOWN prob  : {probability[0]*100:.1f}%")
    print(f"\n⚠️  Disclaimer: For educational purposes only. Not financial advice.")
    return prediction, probability

prediction, probability = predict_tomorrow(model, df, scaler)

def plot_predictions(df, y_test, y_pred):
    test_df             = df.iloc[-len(y_test):].copy()
    test_df['Actual']   = y_test.values
    test_df['Predicted']= y_pred

    correct = (test_df['Actual'] == test_df['Predicted'])

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=test_df.index, y=test_df['Close'],
        name='Close Price', line=dict(color='white', width=1.5)
    ))

    # Correct predictions → green dots
    fig.add_trace(go.Scatter(
        x=test_df[correct].index,
        y=test_df[correct]['Close'],
        mode='markers', name='✅ Correct',
        marker=dict(color='lime', size=8, symbol='circle')
    ))

    # Wrong predictions → red dots
    fig.add_trace(go.Scatter(
        x=test_df[~correct].index,
        y=test_df[~correct]['Close'],
        mode='markers', name='❌ Wrong',
        marker=dict(color='red', size=8, symbol='x')
    ))

    fig.update_layout(
        title=f"🔮 Prediction Accuracy on Test Set — {TICKER}",
        xaxis_title="Date",
        yaxis_title="Price",
        template="plotly_dark",
        height=500
    )
    fig.show()

plot_predictions(df, y_test, y_pred)

from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# ── Step 1: Train price model ──────────────────────────────
df_reg                 = df.copy()
df_reg['Target_Price'] = df_reg['Close'].shift(-1)
df_reg.dropna(inplace=True)

X_reg        = df_reg[FEATURES]
y_reg        = df_reg['Target_Price']
X_reg_scaled = scaler.transform(X_reg)
split        = int(len(X_reg) * 0.8)

reg_model    = RandomForestRegressor(n_estimators=200, max_depth=10, random_state=42)
reg_model.fit(X_reg_scaled[:split], y_reg.iloc[:split])

mae  = np.mean(np.abs(y_reg.iloc[split:].values - reg_model.predict(X_reg_scaled[split:])))
print(f"✅ Price model trained! MAE: ${mae:.2f}")

# ── Step 2: Predict next 7 days (simple version) ───────────
current_price = df['Close'].iloc[-1]
latest_scaled = scaler.transform(df[FEATURES].iloc[-1:])
base_pred     = reg_model.predict(latest_scaled)[0]

# Simple projection using momentum
predictions   = [base_pred + (i * (base_pred - current_price) * 0.1) for i in range(7)]
future_dates  = pd.bdate_range(start=df.index[-1] + pd.Timedelta(days=1), periods=7)

print(f"\n🔮 7-Day Forecast — {TICKER}")
print(f"   Current Price: ${current_price:.2f}\n")
for d, p in zip(future_dates, predictions):
    change = (p - current_price) / current_price * 100
    arrow  = "📈" if p > current_price else "📉"
    print(f"   {d.strftime('%Y-%m-%d')}  →  ${p:.2f}  ({change:+.2f}%)  {arrow}")

# ── Step 3: Plot ────────────────────────────────────────────
hist = df['Close'].tail(60)

plt.style.use('dark_background')
fig, ax = plt.subplots(figsize=(14, 5))

# Historical
ax.plot(hist.index, hist.values, color='cyan', linewidth=2, label='Historical')

# Connector
ax.plot([hist.index[-1], future_dates[0]],
        [hist.values[-1], predictions[0]],
        color='grey', linestyle='dotted')

# Forecast
ax.plot(future_dates, predictions,
        color='orange', linewidth=2,
        linestyle='dashed', marker='o', markersize=8, label='Forecast')

# Annotate prices
for d, p in zip(future_dates, predictions):
    ax.annotate(f'${p:.1f}', xy=(d, p),
                xytext=(0, 10), textcoords='offset points',
                ha='center', fontsize=8, color='orange')

ax.axhline(y=current_price, color='white', linestyle='--',
           alpha=0.4, label=f'Current ${current_price:.2f}')

ax.set_title(f'📈 {TICKER} — 7-Day Price Forecast', fontsize=14)
ax.set_xlabel('Date')
ax.set_ylabel('Price (USD)')
ax.legend()
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
print("✅ Done!")

def plot_model_comparison(X_test, y_test, rf_model, xgb_model, ensemble_model):
    models = {
        'Random Forest' : rf_model,
        'XGBoost'       : xgb_model,
        'Ensemble'      : ensemble_model
    }

    names, accs, up_prec, down_prec = [], [], [], []

    for name, m in models.items():
        pred   = m.predict(X_test)
        report = classification_report(y_test, pred, output_dict=True)
        names.append(name)
        accs.append(accuracy_score(y_test, pred) * 100)
        up_prec.append(report['1']['precision'] * 100)
        down_prec.append(report['0']['precision'] * 100)

    x      = np.arange(len(names))
    width  = 0.25

    plt.style.use('dark_background')
    fig, ax = plt.subplots(figsize=(12, 6), facecolor='#1a1a2e')
    ax.set_facecolor('#16213e')

    ax.bar(x - width, accs,       width, label='Accuracy %',   color='cyan')
    ax.bar(x,         up_prec,    width, label='UP Precision',  color='lime')
    ax.bar(x + width, down_prec,  width, label='DOWN Precision',color='orange')

    ax.set_xticks(x)
    ax.set_xticklabels(names, color='white', fontsize=12)
    ax.tick_params(colors='white')
    ax.set_ylim(0, 100)
    ax.set_ylabel('Score %', color='white')
    ax.set_title('📊 Model Comparison', color='white', fontsize=14)
    ax.legend(facecolor='#1a1a2e', labelcolor='white')
    ax.axhline(y=50, color='red', linestyle='--', alpha=0.4, label='Baseline (50%)')
    for spine in ax.spines.values():
        spine.set_edgecolor('#444')
    plt.tight_layout()
    plt.show()
    print("✅ Best model to use: Ensemble!")

plot_model_comparison(X_test, y_test, rf_model, xgb_model, ensemble_model)

def predict_tomorrow_best(ensemble_model, df, scaler):
    latest        = df[FEATURES].iloc[-1:]
    latest_scaled = scaler.transform(latest)
    pred          = ensemble_model.predict(latest_scaled)[0]
    proba         = ensemble_model.predict_proba(latest_scaled)[0]
    direction     = "📈 UP" if pred == 1 else "📉 DOWN"
    confidence    = max(proba) * 100

    print(f"\n🔮 Final Prediction for {TICKER} (Ensemble Model):")
    print(f"   Direction   : {direction}")
    print(f"   Confidence  : {confidence:.1f}%")
    print(f"   UP  prob    : {proba[1]*100:.1f}%")
    print(f"   DOWN prob   : {proba[0]*100:.1f}%")
    print(f"\n⚠️  For educational purposes only.")

predict_tomorrow_best(ensemble_model, df, scaler)